### ISSUE TITLE
The relationship of the references to the code

### ISSUE THREAD

**Issue by chennnnnyize-zz** [yihui-he/GAN-MNIST#8]
What's the relationship between this code repo and the paper suggested for citation?

**Comment by ethanhe42** [comment]
This code was created when we tested pruning GAN.

**Comment by chennnnnyize-zz** [comment]
It seems GAN never appeared or was discussed in the paper actually...At least some pruning results on GAN shall be discussed under this Repo?

**Comment by ethanhe42** [comment]
Right. The results were not promising so we decided not to show them.

**Comment by chennnnnyize-zz** [comment]
Cool. Interesting reference.
